# -*- coding: utf-8 -*-
"""Bachelor thesis without user.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UqkVq6qp8dHzKjTy7t27ISAbkp-kTzfX
"""

import yfinance as yf
import pandas as pd
import numpy as np
import IPython as ip
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from IPython.display import display
import networkx as nx

tickers = """
SPY VTI VXUS
TLT IEF SHY TIP VTIP LQD BND
GLD SLV
XLV XLU XLP VDC
USMV SPLV
SCHD DGRO VIG
VNQ
DBC PDBC
DBMF KMLM CTA
""".split()
#tickers = "SPY QQQ IWM EFA EEM TLT LQD GLD USO VNQ XLV XLU".split()
#SPY can not be removed

info_keys = [
    "shortName","longName","quoteType","category","fundFamily","currency",
    "exchange","market","country","region","sector","industry",
    "assetClass","legalType","totalAssets","navPrice","yield",
    "expenseRatio","beta3Year","fiveYearAverageReturn","threeYearAverageReturn"
]

def valid(x):
    return pd.notna(x) and str(x).strip() not in ["", "None", "nan", "NaN"]

infos, prices = [], {}

for t in tickers:
    x = yf.Ticker(t)
    inf = x.info

    row = {"ticker": t}
    for k in info_keys:
        v = inf.get(k)
        if valid(v):
            row[k] = v

    infos.append(row)

    h = x.history(period="max", interval="1d", auto_adjust=True)
    if not h.empty and "Close" in h:
        prices[t] = h["Close"].dropna()

# Дані цін
prices_df = pd.concat(prices, axis=1)
prices_df.index = prices_df.index.tz_localize(None)

# 1) Список активів з характеристиками, без колонок, які повністю None / пусті
print("На дашборд бачу доцільним вивести назви тікерів, короткі назви, тип активу та категорію. \nЧастку в портфелі лише якщо не всі активи будуть рівні.\n")
assets = pd.DataFrame(infos)

empty_cols = [
    c for c in assets.columns
    if c != "ticker" and assets[c].map(valid).sum() == 0
]

assets = assets.drop(columns=empty_cols)

# Динамічна рівна частка кожного активу в портфелі
assets["Ratio"] = 1 / len(assets)

display(assets)

# 2) Дані для подальшого аналізу диверсифікації портфеля
print("Виводитись не буде, це ілюстрація датасету, з яким будемо працювати.\n")
returns_df = prices_df.pct_change().dropna(how="all")

portfolio_data = {
    "assets": assets,
    "prices": prices_df,
    "daily_returns": returns_df,
    "weights": assets.set_index("ticker")["Ratio"]
}

display(prices_df.tail())
display(returns_df.tail())
display(portfolio_data["weights"].to_frame("Ratio"))

# 3) Графік росту кожного активу з першого дня його історії: старт = 100
print("Виводитись не буде, це ілюстрація активів, з яким будемо працювати.\n")
growth = prices_df.apply(lambda s: s / s.dropna().iloc[0] * 100 if s.notna().any() else s)

plt.figure(figsize=(14, 7))
growth.plot(ax=plt.gca(), linewidth=1.5)
plt.title("Динаміка росту ETF з першої доступної дати, старт = 100")
plt.xlabel("Дата")
plt.ylabel("Індексована ціна, старт = 100")
plt.grid(True, alpha=0.3)
plt.legend(ncol=3)
plt.show()

# 5) Диверсифікація через кореляцію: матриця кореляцій денних дохідностей
print("Найбільш прямолінійне і зображення кореляції, проте може бути не очевидним для зовнішнього користувача, тому схиляюсь до альтернативного способу.\n")

selected_prices = prices_df[tickers]
corr = selected_prices.pct_change().dropna().corr()

display(corr)

plt.figure(figsize=(10, 8))
plt.imshow(corr, vmin=-1, vmax=1)
plt.colorbar(label="Кореляція")
plt.xticks(range(len(corr.columns)), corr.columns, rotation=45)
plt.yticks(range(len(corr.index)), corr.index)
plt.title("Матриця кореляцій денних дохідностей активів")

for i in range(len(corr.index)):
    for j in range(len(corr.columns)):
        plt.text(j, i, f"{corr.iloc[i, j]:.2f}", ha="center", va="center")

plt.tight_layout()
plt.show()

# Базові дані для всіх наступних графіків
px = prices_df.dropna(how="all").copy()
rets = px.pct_change()
log_rets = np.log(px / px.shift(1))
common_px = px.dropna()
common_rets = common_px.pct_change().dropna()

# ============================================================
# 1. Normalized returns, логарифмічна шкала
# ============================================================
print("Буде виведено як ілюстрація дохідності активів, зображених на дашборді.\n")

normalized = px.apply(lambda s: s / s.dropna().iloc[0] * 100 if s.notna().any() else s)

plt.figure(figsize=(14, 7))
normalized.plot(ax=plt.gca(), linewidth=1.5)
plt.yscale("log")
plt.title("Normalized returns, логарифмічна шкала, старт = 100")
plt.xlabel("Дата")
plt.ylabel("Індексована ціна, log scale")
plt.grid(True, alpha=0.3)
plt.legend(ncol=3)
plt.show()

# ============================================================
# 2. Rolling correlation: динаміка зв'язків активів із SPY
# ============================================================
print("Буде виведено як ілюстрація зміни кореляції активів в часі, дуже важливо бачити, що після 2020 негативна кореляція це виняткова річ.\n")

benchmark = "SPY"
window = 252   # приблизно 1 торговий рік

rolling_corr = pd.DataFrame({
    t: common_rets[t].rolling(window).corr(common_rets[benchmark])
    for t in common_rets.columns
    if t != benchmark
})

plt.figure(figsize=(14, 7))
rolling_corr.plot(ax=plt.gca(), linewidth=1.3)
plt.axhline(0, linestyle="--", linewidth=1)
plt.title(f"Rolling correlation з {benchmark}, вікно = {window} торгових днів")
plt.xlabel("Дата")
plt.ylabel("Кореляція")
plt.grid(True, alpha=0.3)
plt.legend(ncol=3)
plt.show()

# ============================================================
# 3. PCA-карта активів
# хто поруч → більше схожий / корелює
# хто далеко → краще диверсифікує
# ============================================================
print("Буде виведено як ілюстрація кореляції замість матриці, бо дуже прямолінійно бачити групи активів, які корелюють одне з одним.\n")

X = common_rets.dropna().T
X_scaled = StandardScaler().fit_transform(X)

pca = PCA(n_components=2)
coords = pca.fit_transform(X_scaled)

pca_df = pd.DataFrame(
    coords,
    index=X.index,
    columns=["PC1", "PC2"]
)

display(pca_df)

plt.figure(figsize=(10, 8))
plt.scatter(pca_df["PC1"], pca_df["PC2"], s=120)

for t in pca_df.index:
    plt.text(
        pca_df.loc[t, "PC1"],
        pca_df.loc[t, "PC2"],
        " " + t,
        fontsize=11,
        va="center"
    )

plt.axhline(0, linewidth=1, alpha=0.5)
plt.axvline(0, linewidth=1, alpha=0.5)
plt.title("PCA-карта активів за денними дохідностями")
plt.xlabel(f"PC1, {pca.explained_variance_ratio_[0]:.1%} variance")
plt.ylabel(f"PC2, {pca.explained_variance_ratio_[1]:.1%} variance")
plt.grid(True, alpha=0.3)
plt.show()

# ============================================================
# 4. Network graph: візуалізація кореляцій
# ============================================================
print("Не буде виведено як ілюстрація кореляції активів, бо для читання треба дуже детально усі відстані читати і опрацьовувати, до купи не очевидно наскільки далеко по зв'язку активи, які не включаються у зв'язки.\n")

corr = common_rets.corr()

threshold = 0.55   # показувати тільки сильніші зв'язки
G = nx.Graph()

for t in corr.columns:
    G.add_node(t)

for i in corr.columns:
    for j in corr.columns:
        if i < j and abs(corr.loc[i, j]) >= threshold:
            G.add_edge(i, j, weight=corr.loc[i, j])

pos = nx.spring_layout(G, seed=42, k=0.7)

plt.figure(figsize=(11, 9))

edge_widths = [
    abs(G[u][v]["weight"]) * 4
    for u, v in G.edges()
]

nx.draw_networkx_nodes(G, pos, node_size=1200)
nx.draw_networkx_edges(G, pos, width=edge_widths, alpha=0.6)
nx.draw_networkx_labels(G, pos, font_size=11)

edge_labels = {
    (u, v): f"{G[u][v]['weight']:.2f}"
    for u, v in G.edges()
}

nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_size=9)

plt.title(f"Network graph кореляцій, |corr| >= {threshold}")
plt.axis("off")
plt.show()

# ============================================================
# 5. Drawdown overlay
# ============================================================
print("Загальна діаграма drawdown, не буде виведено на дашборд, через великі стрибки не виконує задачу ілюстрації які активи просідають найбільше, які балансують. \n")

wealth = normalized / 100
running_max = wealth.cummax()
drawdown = wealth / running_max - 1

plt.figure(figsize=(14, 7))
drawdown.plot(ax=plt.gca(), linewidth=1.3)
plt.title("Drawdown overlay активів")
plt.xlabel("Дата")
plt.ylabel("Drawdown")
plt.grid(True, alpha=0.3)
plt.legend(ncol=3)
plt.show()


# Додатково: drawdown портфеля з поточними Ratio
print("Якщо ratio буде вираховуватись окремою формулою і буде цінним, то графік буде виведено на дашборд. \n")
w = assets.set_index("ticker")["Ratio"].reindex(common_px.columns).fillna(0)
w = w / w.sum()

portfolio_rets = common_rets.mul(w, axis=1).sum(axis=1)
portfolio_wealth = (1 + portfolio_rets).cumprod()
portfolio_drawdown = portfolio_wealth / portfolio_wealth.cummax() - 1

plt.figure(figsize=(14, 6))
portfolio_drawdown.plot(linewidth=2.5)
plt.title("Drawdown портфеля з урахуванням Ratio")
plt.xlabel("Дата")
plt.ylabel("Portfolio drawdown")
plt.grid(True, alpha=0.3)
plt.show()

#drawdown згладжений

# ============================================================
# 5. Drawdown overlay (smoothed for regime analysis)
# ============================================================

print("Буде використано для ілюстрації які активи просідають менше у кризові періоди, або навіть ростуть, коли все навколо падає\n")


# 1) Переводимо нормалізовану ціну у "wealth"
wealth = normalized / 100

# 2) Згладжуємо wealth (прибираємо денний шум)
span = 30  # можна 20–60 (менше = чутливіше, більше = плавніше)
wealth_smooth = wealth.ewm(span=span, adjust=False).mean()

# 3) Будуємо running max вже по згладженій кривій
running_max = wealth_smooth.cummax()

# 4) Drawdown
drawdown_smooth = wealth_smooth / running_max - 1

# ============================================================
# Візуалізація
# ============================================================

plt.figure(figsize=(14, 7))
drawdown_smooth.plot(ax=plt.gca(), linewidth=1.8, alpha=0.85)

plt.title("Smoothed Drawdown overlay (EMA wealth, span=30)")
plt.xlabel("Дата")
plt.ylabel("Drawdown")
plt.grid(True, alpha=0.3)
plt.legend(ncol=3)

plt.show()

# ============================================================
# 6. Relative performance проти SPY
# ============================================================
print("не буде використано, бо перформанс рахується комулятивним чином, відповідно один успіх в минулому може перекривати цінність прямо зараз\n")

spy_norm = normalized[benchmark]

relative_to_spy = normalized.div(spy_norm, axis=0) * 100
relative_to_spy = relative_to_spy.drop(columns=[benchmark], errors="ignore")

plt.figure(figsize=(14, 7))
relative_to_spy.plot(ax=plt.gca(), linewidth=1.3)
plt.axhline(100, linestyle="--", linewidth=1)
plt.title(f"Relative performance проти {benchmark}, {benchmark} = 100")
plt.xlabel("Дата")
plt.ylabel(f"Відносна сила проти {benchmark}")
plt.grid(True, alpha=0.3)
plt.legend(ncol=3)
plt.show()

print("Додаю на дашборд, дійсно показує у перспективі 3 років, що перекриває спади SPY, відповідно буде чудовим доповненням у кризовий період\n")
# ============================================================
# 7. Rolling Relative Performance vs SPY
# ============================================================

print("""
Rolling relative performance показує:
які активи outperform / underperform SPY
за останні N років, а не за всю історію.
""")

window_years = 3
window = 252 * window_years

# rolling growth за вікно
rolling_growth = px / px.shift(window)

# relative performance vs SPY
rolling_rel = rolling_growth.div(
    rolling_growth[benchmark],
    axis=0
).drop(columns=benchmark)


plt.figure(figsize=(14, 7))

rolling_rel.plot(
    ax=plt.gca(),
    linewidth=1.5
)

plt.axhline(1, linestyle="--", linewidth=1)

plt.title(
    f"Rolling Relative Performance vs {benchmark} "
    f"({window_years}Y)"
)

plt.xlabel("Дата")
plt.ylabel("Relative strength")

plt.grid(True, alpha=0.3)
plt.legend(ncol=3)

plt.show()

